export const CUSTOM_ERROR_MESSAGES = {
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
};

export const UserRole = {
  PROFESSOR: "PROFESSOR",
  STUDENT: "STUDENT",
};

export const DissertationRequestStatus = {
  PENDING_APPROVAL: "PENDING APPROVAL",
  APPROVED: "APPROVED",
  DECLINED: "DECLINED",
  APPROVED_REJECTED: "APPROVED_REJECTED",
  FILE_UPLOADED_BY_STUDENT: "FILE UPLOADED BY STUDENT",
  FILE_UPLOADED_BY_PROFESSOR: "FILE UPLOADED BY PROFESSOR",
};

export const ONE_MEGABYTE = 1000000;

export const MAX_NUMBER_OF_STUDENTS_PER_PROFESSOR = 5;
